modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/MonsterEggs/issues"
license="MIT"

[[mods]]
modId="monstereggs"
version="${file.jarVersion}"
displayName="Monster Eggs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/monster-eggs"
authors="Mrbysco, ShyNieke"
description='''
Don't mind me, just adding some monster eggs to the underground.
'''
[[dependencies.monstereggs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.monstereggs]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"